In [3]:
import numpy as np
import torch

In [6]:
torch.rand(5, 3).numpy()

[array([0.01560026, 0.14899027, 0.8198149 ], dtype=float32),
 array([0.9768128 , 0.06915247, 0.42297667], dtype=float32),
 array([0.9447805 , 0.9968865 , 0.85253155], dtype=float32),
 array([0.4674251, 0.9449542, 0.6850118], dtype=float32),
 array([0.8488321 , 0.9191937 , 0.33687925], dtype=float32)]

In [7]:
x = torch.rand(5, 3).numpy()

In [8]:
[list(x[i]) for i in range(x.shape[0])]

[[0.6611388, 0.24161768, 0.35973948],
 [0.28449154, 0.81414443, 0.17932409],
 [0.65817285, 0.1036877, 0.8726997],
 [0.05815494, 0.3649323, 0.6273505],
 [0.57139295, 0.16107935, 0.08857018]]